name: Release app to ECS

on:
  push:
    branches:
      - main

env:
  TF_LOG: INFO
  TF_INPUT: false

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ${{ secrets.DOCKER_IMAGE }}:${{ github.sha }}

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4.1.0
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: setup terraform
        uses: hashicorp/setup-terraform@v3

      - name: initialize terraform
        working-directory: terraform
        run: terraform init
        env:
          TF_VAR_AWS_REGION: ${{ secrets.AWS_REGION }}

      - name: terraform plan
        working-directory: terraform
        run: terraform plan -out plan.out
        env:
          TF_VAR_image: ${{ secrets.DOCKER_IMAGE }}:${{ github.sha }}
          TF_VAR_AWS_REGION: ${{ secrets.AWS_REGION }}
